### ISSUE TITLE
Frequency band operators

### ISSUE THREAD

**Issue by teonbrooks** [neurosity/openbci-observable#17]
Do you think it would be more general to have a bandpass with the lower and upper limit and a label versus have the frequency ranges predefined (e.g. alpha, delta, gamma, etc.)?

**Comment by alexcastillo** [comment]
I'm panning to add a bandpass operator with lower and upper limit but I think predefine frequency ranges are useful shortcuts for beginners.

**Comment by teonbrooks** [comment]
closing as this is now solved with eegpipes
